### ISSUE TITLE
stub effects outside intended context

### ISSUE THREAD

**Issue by infotroph** [r-lib/mockery#20]
I'm not sure if this is one bug or several (or zero!), but these are three bits of behavior I wasn't expecting that all came up while debugging one issue in my own code, so here they are together.

1. Stubs with depth > 1 remain in effect outside the function that defined them:
	```
	h = function()1
	g = function()h()
	f = function()g()

	test_that("stubbing works in a non-nested function", {
		expect_equal(g(), 1)
		stub(g, "h", 2)
		expect_equal(g(), 2)
	})
	test_that("stubs do not carry over between test blocks", {
		expect_equal(g(), 1)
	})

	test_that("stubbing works inside a nested function", {
		expect_equal(f(), 1)
		stub(f, "h", 2, depth=2)
		expect_equal(f(), 2) 
	})
	test_that("nested stubs do not carry over between test blocks", {
		expect_equal(f(), 1) # FAILS: h is still stubbed
	})
	```

2. Stubs with depth > 1 can affect calls not in `what`:
	```
	g = function(y) y
	f = function(x) g(x) + 1
	r = function(x) g(x) + f(x)
	test_that('only calls from what are stubbed', {
		stub(r, 'g', 100, depth=2)
		expect_equal(r(1), 201)
		expect_equal(g(1), 1)
		expect_equal(f(1), 2) # FAILS: uses stubbed g
	})
	```

3. When stubs are called from within functions defined outside of the test, only the first-defined stub is used:
	```
	f = function(x) x + 10
	g = function(y) y + 20
	h = function(z) f(z) + g(z)
	u = function(zz)h(zz)
	test_that('multiple stubs defined in test work with functions defined outside test', {
		
		u_local = function(zz)h(zz)

		stub(h, 'f', 300)
		stub(h, 'g', 500)

		expect_equal(h(1), 800)
		expect_equal(u_local(1), 800)
		expect_equal(u(1), 800) # FAILS: uses unstubbed version of g
	})
	```
	An apparent workaround is to define the stubs outside of the test function:
	```
	f = function(x) x + 10
	g = function(y) y + 20
	h = function(z) f(z) + g(z)
	u = function(zz)h(zz)
	stub(h, 'f', 300)
	stub(h, 'g', 500)
	test_that('multiple stubs defined outside of test work with functions defined outside test', {

		u_local = function(zz)h(zz)

		expect_equal(h(1), 800)
		expect_equal(u_local(1), 800)
		expect_equal(u(1), 800)
	})
	```

* * * 

```
> devtools::session_info()
Session info ----------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, darwin15.6.0        
 ui       AQUA                        
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2017-12-09                  

Packages --------------------------------------------------------------------------------
 package    * version date       source         
 base       * 3.4.2   2017-10-04 local          
 compiler     3.4.2   2017-10-04 local          
 crayon       1.3.4   2017-09-16 CRAN (R 3.4.1) 
 datasets   * 3.4.2   2017-10-04 local          
 devtools     1.13.3  2017-08-02 CRAN (R 3.4.1) 
 digest       0.6.12  2017-01-27 CRAN (R 3.4.0) 
 graphics   * 3.4.2   2017-10-04 local          
 grDevices  * 3.4.2   2017-10-04 local          
 magrittr     1.5     2014-11-22 CRAN (R 3.4.0) 
 memoise      1.1.0   2017-04-21 CRAN (R 3.4.0) 
 methods    * 3.4.2   2017-10-04 local          
 mockery    * 0.4.1   2017-11-10 CRAN (R 3.4.2) 
 R6           2.2.2   2017-06-17 CRAN (R 3.4.0) 
 Rcpp         0.12.13 2017-09-28 cran (@0.12.13)
 rstudioapi   0.7     2017-09-07 cran (@0.7)    
 stats      * 3.4.2   2017-10-04 local          
 testthat   * 1.0.2   2016-04-23 CRAN (R 3.4.0) 
 utils      * 3.4.2   2017-10-04 local          
 withr        2.0.0   2017-07-28 CRAN (R 3.4.1) 
```

**Comment by n-s-f** [comment]
@infotroph Thanks very much for writing up these examples.  

I'm not sure I'll be able to provide fixes in the immediate future, but if you're up for the task of trying to write the fixes yourself I'd be happy to provide some pointers.  A great way to start would be to open up a new branch, add these test cases you've already written to the test suite, and see if you can get some of them to pass. I'll jump in when I can.

The first two look like bugs. The depth option is new, and I'm sure there are more kinks to work out.

The third looks bug-ish, but the failing case is not really the intended way to use the stub function. If you're going to call `u`, and you want `f` and `g` to be stubbed, then the proper way to do it would be something like `stub(u, 'f', 300, depth=2)` and `stub(u, 'g', 500, depth=2)`. In principle the current test should actually use the unstubbed versions of _both_ `f` and `g` - I can look into why that's not the case.

**Comment by infotroph** [comment]
@n-s-f In principle I'm interested in working on a fix -- it'd be a good way to improve my understanding of how environments interact -- but not sure when I'll have bandwidth to tackle it. Once I get as far as a branch, I'll report back here.

**Comment by infotroph** [comment]
Meanwhile, for the third case I think I wrote my test case around a different issue I hadn't identified at the time, which is that stubbing namespaced calls doesn't seem to work at depth > 1: 

```
test_that('stubs function from namespace at depth > 1', {
    # given
    f = function() testthat::capture_output(print('hello'))
    g = function() f()

    # before stubbing
    expect_true(grepl('hello', g()))

    # when
    stub(g, 'testthat::capture_output', 'goodbye', depth = 2)

    # then
    expect_equal(g(), 'goodbye') # FAILS: capture_output not stubbed
})
```

In my current project I worked around this by using a really ugly [nested stub call](https://github.com/PecanProject/pecan/blob/362a81a1a365e1077e47e4377f266b2f07f107a8/models/biocro/tests/testthat/test-run.biocro.R#L26-L31), though maybe the real problem there is me trying to test too big a unit.

**Comment by Blackglade** [comment]
was this ever resolved? Having the same issues

**Comment by sgsmob** [comment]
> was this ever resolved? Having the same issues

+1

**Comment by deril2605** [comment]
> was this ever resolved? Having the same issues

+1 I am facing the same issue

**Comment by averissimo** [comment]
I've avoided this bug by doing a _"manual"_ depth stub.

In the example below I'm trying to mock `cli_h2` inside `length_log`. However, `length_log` is called via `xportr_length`

```
if (require(mockery, quietly = TRUE)) {
    # Prevent CLI messages by using local xportr_logger instead
    stub(length_log, "cli_h2", cli_mocked_fun)
    stub(xportr_length, "length_log", length_log)
  }
```
