### ISSUE TITLE
depth not working? cannot change value of locked binding for '.onLoad'

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/mockery#30]
I have a package (https://github.com/MichaelChirico/geohashTools) where several functions rely on Suggested packages.

At the top of such functions, I do a `requireNamespace(pkg)` check & error if the Suggested package isn't installed.

Earlier, I was doing coverage tests for these by (e.g. for function `foo`)

```
stub(foo, requireNamespace, FALSE)
testthat::expect_error(foo(x), 'please install')
```

There are enough functions like this now that I split off this test into a helper function (_unexported_):

```
check_suggested = function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop("This function requires an installation of ", pkg,
         "; install.packages('", pkg, "') to proceed.")
  }
}
```

The old tests fail, I assume because the stubbing is only done _directly_ in the environment of `foo`, so when `foo` calls `check_suggested`, `requireNamespace` operates as normal.

So I tried to stub `check_suggested`:

```
stub(geohashTools:::check_suggested, requireNamespace, FALSE)
```

But this didn't work -- the code `foo(x)` runs without error.

Then I came across the `depth` argument which looked promising, but it's giving me a strange error:

```
stub(geohashTools:::check_suggested, 'requireNamespace', FALSE, depth = 2L)
```

> Error in assign(where_name, func, parent_env) : 
  cannot change value of locked binding for '.onLoad'

Am I using the argument wrong? How should I go about stubbing in this case to mock an environment where a suggested package is not installed?

**Comment by jimhester** [comment]
I am pretty sure that `stub(geohashTools:::check_suggested, "requireNamespace", FALSE)` would work, note the second argument should be the name of the function, not the function object, perhaps that was the issue.

**Comment by MichaelChirico** [comment]
I don't think so... see here:

https://github.com/MichaelChirico/geohashTools/pull/23

I `stub(geohashTools:::check_suggested)` and then run `expect_error` on a function (`gh_to_sp`) that calls `check_suggested`... not getting the expected error though.

**Comment by jimhester** [comment]
```r
mockery::stub(check_suggested, 'requireNamespace', FALSE, depth = 2)
```

Works for me with the current version of mockery, though it seems to persist beyond the test_that block so other tests later in the file then fail.

**Comment by AlexandraKapp** [comment]
I get a similar error: 

If I run the test with testthat::test() or testthat::test_package() it works just fine. 
But when I run devtools::check() I get the error:

```
cannot change value of locked binding for '%not_in%'
Backtrace:
 1. mockery::stub(...)
 2. mockery:::mock_through_tree(tree, what, how)
 3. base::assign(where_name, func, parent_env)
```

code (simplified):
```
parent_function <- function (x) {
  return (child_function())
}

child_function <- function (x)  {
  return (grandchild_function())
}

grandchild_function <- function() {
  return (FALSE)
}

test_that("desc", {
  stub(child_function, "grandchild_function", TRUE, depth = 2)
  
  expect(parent_function(), TRUE)
})

```

Any idea how that could be fixed?

**Comment by Toekan** [comment]
Encountering exactly the same problem. Mocking works without the `depth` parameter, but the moment I need depth value > 1 I get the above mentioned error. I'm using mockery 0.4.2, which seems to be the latest version?

Can we reopen this issue?

**Comment by sambrightman** [comment]
I'm having the same issue and think this needs re-opening. @nsfinkelstein says in https://github.com/r-lib/mockery/issues/29#issuecomment-485467496 that second-level functions need to use `depth=2`. However, this issue means that using `depth=2` will break tests e.g. under `covr` or `R CMD check`.

**Comment by sambrightman** [comment]
For my case, the stack trace indicates that a function is being assigned that is not the function being mocked. I'm not sure if this is expected behaviour.

```cannot change value of locked binding for 'marker_message'
Backtrace:
 1. mockery::stub(...)
 2. mockery:::mock_through_tree(tree, what, how)
 3. base::assign(where_name, func, parent_env)
```

Based on this stack trace, I think that `parent_env` here is that of the package under test and is therefore locked. I tried a quick workaround:

```diff --git R/stub.R R/stub.R
index c85ad56..1aa2c12 100644
--- R/stub.R
+++ R/stub.R
@@ -84,7 +84,14 @@ mock_through_tree <- function(tree, what, how) {
                 }

                 environment(func) <- func_env
+                locked <- exists(where_name, parent_env, inherits = FALSE) && bindingIsLocked(where_name, parent_env)
+                if (locked) {
+                  unlockBinding(where_name, parent_env)
+                }
                 assign(where_name, func, parent_env)
+                if (locked) {
+                  lockBinding(where_name, parent_env)
+                }
             }
         }
   }```

This fixed my issue and passes existing tests. I'm not very familiar with environment manipulation but can make a PR of this is it seems suitable.

**Comment by sambrightman** [comment]
It might be that some tests are missing too of course - it was [mentioned previously](https://github.com/r-lib/mockery/issues/17#issuecomment-267765998) that locked environment tests should be added and I think they are not.

**Comment by njtierney** [comment]
@hadley do you know if there is a timeline on when this will be submitted to CRAN or if there is something we can help with? 

It looks like it got a bit stalled at submitting to CRAN late last year (https://github.com/r-lib/mockery/issues/55)

Happy to help contribute if there's something I can help with!

**Comment by hadley** [comment]
Sorry for missing this. I'll take it over.

**Comment by njtierney** [comment]
Fantastic! Sorry to bother you on a closed issue, thank you for the swift reply!
