### ISSUE TITLE
Multiple stubs

### ISSUE THREAD

**Issue by damianooldoni** [r-lib/mockery#37]
First of all, `stub()` is wonderful! Easy to use, intuitive, just great. :clap: 
I searched how to stub multiple functions and I was struggling on it. Then, I found it, just use `stub()` twice:

```r
f <- function(date = Sys.Date()) {
    print(date)
    readline("Get your opinion about!")
  }  
stub(where = f, what = 'Sys.Date', how = as.Date('1900-01-01'))
stub(where = f, what = 'readline', how = "Nice!")
```
Is there a way to improve this? Allowing vectors for `what` and `how` maybe?
Something like:
```r
stub(where = f,
     what = c('Sys.Date', 'readline'),
     how = c(as.Date('1900-01-01'), "Nice!"))
```
Anyway, I think that adding a double stubbing example in documentation could help. What do you think about it? Many thanks!

**Comment by jimhester** [comment]
Sure, sounds like a good idea to me, would you like to make a pull request adding the new example?

**Comment by damianooldoni** [comment]
Ok. I'll do.
