### ISSUE TITLE
Stubbing out a function called within S3 dispatch

### ISSUE THREAD

**Issue by nbenn** [r-lib/mockery#43]
I'm running into issues trying to mock a function with S3 dispatch involved. Consider the following setting:

```r
gen <- function(x) UseMethod("gen")

met <- function(x) foo(x)

foo <- function(x) stop("foo")

.S3method("gen", "cls", met)

x <- structure(123, class = "cls")

gen(x)
#> Error in foo(x) : foo
```

I would now like to be able to call `gen(x)` is a test where `foo()` is stubbed out to avoid throwing the error. I assume this is currently not possible using `mockery::stub()`?

```r
mockery::stub(gen, "foo", "bar", depth = 1)

gen(x)
#> Error in foo(x) : foo

mockery::stub(gen, "foo", "bar", depth = 2)

gen(x)
#> Error in foo(x) : foo

mockery::stub(gen, "foo", "bar", depth = 3)

gen(x)
#> Error in foo(x) : foo

# etc...
```

**Comment by jimhester** [comment]
This limitation doesn't really seem to cause many issues in practice, you usually would mock the generic rather than a method.

**Comment by MichaelChirico** [comment]
I just ran into this myself. It's not clear how to use `mockery` to replace `with_mock` here:

https://github.com/r-lib/lintr/blob/aafba478622c6f43c3fb329c69945c36a4d94b68/tests/testthat/test-ci.R#L47-L49

```
    with_mock(github_comment = function(x, ...) cat(x, "\n"), .env = asNamespace("lintr"), {
      expect_output(print(l), "*warning:*", fixed = TRUE)
    })
```

Both of the following failed:

```
foo <- function(x, ...) cat(x, "\n")
mockery::stub(lintr:::print.lints, "github_comment", foo) # lintr:::github_comment executes
mockery::stub(lintr:::print.lints, "github_comment", foo, depth = 2) # error: cannot add bindings to a locked environment
mockery::stub(print, "github_comment", foo, depth = 2L) # weird error "use of NULL environment is defunct"
```

**Comment by nbenn** [comment]
@MichaelChirico I started to roll my own, as I was not happy with what {mockery} and {mockr} offered in terms of functionality: {[mockthat](https://nbenn.github.io/mockthat/)}. Has worked fine for my own use so far, but I'm sure there are edge-cases, that will break things for my approach too. Happy to take [feedback/issues/etc](https://github.com/nbenn/mockthat/issues/new/).
