### ISSUE TITLE
Multiple stub/mocks within a function fails at depth >= 2

### ISSUE THREAD

**Issue by kbaynes** [r-lib/mockery#46]
There appears to be a bug with r-lib/mockery `expect_called()` and `stub()` for multiple functions at depth >=2. `stub()` and `expect_called()` works as expected for multiple functions at a depth of 1. At depth >= 2, the first stubbed/mocked function (A) is called (works as expected), but the subsequent stubbed/mocked functions (B,C,...) are not called, instead the actual function is called. Either there is a bug, or I do not understand something. :-)

Please see my [project demonstrating the behavior](https://github.com/kbaynes/R-mockery-test).

Example: `mD2A` mock is called, but `mD2B` is not called.

```
    print("can stub multiple functions at depth=2")
    source("multiFuncD2.R")
    mD2A <- mock(TRUE)
    mD2B <- mock(TRUE)
    stub(Depth0.myFunction,'Depth2.myFunctionA',mD2A,depth=2)
    stub(Depth0.myFunction,'Depth2.myFunctionB',mD2B,depth=2)
    Depth0.myFunction()
    expect_called(mD2A,1)
    expect_called(mD2B,1)
```

**Comment by kbaynes** [comment]
Adding the following test to r-lib/mockery/tests/testthat/test_stub.R demonstrates the behavior:

```
test_that('stub multiple functions at depth >= 2', {
  # given
  f = function(x) x + 10
  g = function(y) y + 20
  h = function(z) f(z) + g(z)
  i = function(zz) h(zz)  
  
  # when
  stub(i, 'f', 300, depth=2)
  stub(i, 'g', 500, depth=2)
  
  # then
  expect_equal(h(1), 800)
})
```

**Comment by lorenzwalthert** [comment]
I agree. This is a major limitation.

**Comment by hadley** [comment]
We now recommend `testthat::local_mocked_bindings()` as it doesn't have this problem.
