### ISSUE TITLE
mockery vs mockthat

### ISSUE THREAD

**Issue by brianrepko** [r-lib/mockery#48]
Hi @krlmlr - I'm wondering if you can share thoughts on `mockery` vs `mockthat` and which might become the "official" replacement for `testthat`'s dropping of mocking.

`mockery` seems to be already under `r-lib` so that has me thinking it is more "official" but `mockthat` has more recent  updates.

I'll post a similar issue for mockthat.

**Comment by brianrepko** [comment]
https://github.com/nbenn/mockthat/issues/4

**Comment by hadley** [comment]
`testthat::local_mocked_bindings()` is now the official replacement 😄
