### ISSUE TITLE
Unintuative stub/mock behaviour

### ISSUE THREAD

**Issue by gowerc** [r-lib/mockery#56]
I apologies in advance if this is "expected behaviour" or I am being dim but how `stub` and `mock` work doesn't seem that intuative to me :( 

```
library(mockery)
f <- function() 1
g <- function() f() + 1
h <- function() g() + 1
i <- function() h() + 1
j <- function() i() + 1

mocky <- mock(100, 200)
stub(j, "f", mocky, depth = 2)
j()
#> [1] 104

mocky <- mock(300, 400)
stub(j, "f", mocky, depth = 2)
j()
#> [1] 204
```
> Created on 2021-11-30 by the reprex package (v2.0.1)

* How come the mocking was successful, the `f()` function is called at depth 4 so I wouldn't have expected `depth = 2` to have replaced it. If it is a global replace (at all depths) would it make more sense to convert this to a logical called `recursive` or something similar? 

* I am confused as to why after both overwriting the `mocky` object and re-running `stub()` it still returns the value from the first mocked object ? If I re-run the code to define the functions it works as intended but this isn't really possible when dealing with test_that code

If this is indeed expected behaviour would it be possible to update the documentation to explain why it behaves this way ?

**Comment by FlorianMyronStork** [comment]
@gowerc I have an explanation for your issue, which might also solve this problem: https://github.com/r-lib/mockery/issues/57#issue-1067610442

When you manually load the functions `f, g, h, i` and `j` into your `.GlobalEnv`, then mockery does not clean this up. Those functions get somewhat changed permanently. (Don't know how this works)

If you instead use `devtools::load_all(*.*)` to load your functions into the namespace of your current package (Assuming that you are developing a package - See: https://r-pkgs.org/tests.html) then this issue does not occur any more:

```
library(testthat)
library(mockery)

f <- function() 1
g <- function() f() + 1
h <- function() g() + 1
i <- function() h() + 1
j <- function() i() + 1

ls()
# [1] "f" "g" "h" "i" "j"

describe("mockery in depth", {
  it("should replace only at the given depth", {
    mocky <- mockery::mock(100, 200)
    mockery::stub(j, "f", mocky, depth = 2)
    expect_equal(j(), 104)
    expect_equal(j(), 204)
  })
})
# Test passed

describe("mockery in depth", {
  it("should replace only the given depth", {
    mocky <- mockery::mock(100, 200)
    mockery::stub(j, "f", mocky, depth = 2)
    expect_equal(j(), 104)
    expect_equal(j(), 204)
  })
})

# -- Failure (Line 5): mockery in depth: should replace only the given depth ---------------------
#   too many calls to mock object and cycle set to FALSE
# Backtrace:
#   1. testthat::expect_equal(j(), 104)
# 4. j()
# 5. i()
# 6. h()
# 7. g()
# 8. mockery f()
#
# -- Failure (Line 6): mockery in depth: should replace only the given depth ---------------------
#   too many calls to mock object and cycle set to FALSE
# Backtrace:
#   1. testthat::expect_equal(j(), 204)
# 4. j()
# 5. i()
# 6. h()
# 7. g()
# 8. mockery f()

rm(list = c("f", "g", "h", "i", "j"))
ls()

# character(0)

# Don't put this function in ANY script in the R-Folder! Else it would recursively call itself!
devtools::load_all(".") # needs your functions to live in an .R file in the R-Folder
# i Loading drkleinrkprovisionentool

ls() # To confirm, that the functions don't live in the .GlobalEnv anymore
# character(0)

describe("mockery in depth", {
  it("should replace only at the given depth", {
    mocky <- mockery::mock(100, 200)
    mockery::stub(j, "f", mocky, depth = 2)
    expect_equal(j(), 104)
    expect_equal(j(), 204)
  })
})
# Test passed 

describe("mockery in depth", {
  it("should replace only the given depth", {
    mocky <- mockery::mock(100, 200)
    mockery::stub(j, "f", mocky, depth = 2)
    expect_equal(j(), 104)
    expect_equal(j(), 204)
  })
})
# Test passed 
```

**Comment by hadley** [comment]
We now recommend that you use `testthat::local_mocked_bindings()` instead of mockery; that should resolve this issue.
