### ISSUE TITLE
stub depth > 1 not working for R6 classes

### ISSUE THREAD

**Issue by adamborondy** [r-lib/mockery#62]
I am trying to use `mockery::stub()` in combination with an R6 class, which works out fine for functions at a depth of 1. Here is a simplified R6 example:
```r
library(mockery)

stubTest <- R6::R6Class(classname = "stubTest",
  public =
    list(
      sum = 0,
      add_x = function() {
        self$sum <- self$sum + self$add_y()
        invisible(self)
      },
      add_y = function() {
        self$add_z()
      },
      add_z = function() {
        5
      }
    )
)
```
I can successfully stub `self$add_y` like this:
```r
test_that('Stubbing test depth 1', {
  st <- stubTest$new()
  stub(st$add_x, 'self$add_y', 10, depth = 1)
  st$add_x()
  expect_equal(st$sum, 10)
})
```
However I cannot do the same for  `self$add_z` at a depth of 2. This results in an actual value of 5 as expected without stubbing:
```r
test_that('Stubbing test depth 2', {
  st <- stubTest$new()
  stub(st$add_x, 'self$add_z', 10, depth = 2)
  st$add_x()
  expect_equal(st$sum, 10)
})
```
I'm not sure if this feature is applicable to R6 classes in this way, so I appreciate any feedback!

**Comment by hadley** [comment]
mockery is no longer under active development as we now recommend using `testthat::local_mocked_bindings()` instead. That doesn't yet support mocking R6 methods, but we could certainly consider it if it's a popular need.

**Comment by hadley** [comment]
I've filed an issue to look into this for testthat: https://github.com/r-lib/testthat/issues/1892
