### ISSUE TITLE
How to "unstub" a function?

### ISSUE THREAD

**Issue by daattali** [r-lib/mockery#63]
I want to use `mockery::stub()` in a testthat test, and afterwards (in the same scope) I'd like to revert back to the real un-stubbed function.

For example, I'd like the following to work:

```r
f <- function() 2
g <- function() f()

test_that("it works", {
  mockery::stub(g, "f", 5)
  expect_equal(g(), 5)
  # mockery::unstub(g, "f")
  expect_equal(g(), 2)
})
```

I can currently achieve this by doing `stub(g, "f", f)` but that seems like a poor workaround.

**Comment by hadley** [comment]
The function we now recommend for this is `testthat::with_mocked_bindings()`
