### ISSUE TITLE
Add documentation for how to stub R6 methods

### ISSUE THREAD

**Issue by daattali** [r-lib/mockery#64]
The README simply says "This also works with R6 classes and methods." and there is no other documentation or mentions of R6 anywhere. It would be useful to show an example.

**Comment by maciekbanas** [comment]
E.g. I would like to know how to mock R6 private methods. (is it possible, or only public?)

**Comment by hadley** [comment]
mockery is no longer under active development so I'm closing this issue. We now recommend `testthat::local_mocked_binding()` instead, but unfortunately that doesn't help with R6 (yet).

**Comment by hadley** [comment]
I've filed an issue to look into this for testthat: https://github.com/r-lib/testthat/issues/1892
