### ISSUE TITLE
When `depth=2` all functions with stubbed function are affected

### ISSUE THREAD

**Issue by maciekbanas** [r-lib/mockery#66]
When I stub function with `depth = 1` stubbing concerns correctly only the function **where** I chose to stub it.
```
> z <- function() 10
> f <- function() z()
> g <- function() z()
> mockery::stub(f, "z", 5)
> f()
[1] 5
> g()
[1] 10
```
However, when I stub it with `depth = 2` stubbing concerns also all other functions, which is not desired (I did not choose `g()` to be stubbed here).
```
> y <- function() 10
> z <- function() y()
> f <- function() z()
> g <- function() z()
> mockery::stub(f, "y", 5, depth = 2)
> f()
[1] 5
> g()
[1] 5
```

**Comment by hadley** [comment]
We now recommend using `testthat::local_mocked_binding()` instead; it uses a different approach to mocking that is less vulnerable to the problems that mockery suffers from.
